import mimetypes
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


DEBUG = True
SMTP_SERVER = 'mail.starman.ee'


def send_message(file, addr):
    smtp = smtplib.SMTP(SMTP_SERVER)

    msg = MIMEMultipart('alternative')
    msg['Subject'] = "Autogenerated message from %s" % file
    msg['From'] = addr
    msg['To'] = addr

    content_type, _ = mimetypes.guess_type(file)
    if content_type == 'text/plain':
        with open(file) as f:
            content = f.read()
            msg_body = MIMEText(content)
            msg.attach(msg_body)
    else:
        with open(file, 'rb') as f:
            content = f.read()
            msg_file = MIMEBase('application', 'octet-stream')
            msg_file.set_payload(content)
            encoders.encode_base64(msg_file)
            msg_file.add_header('Content-Disposition', 'attachment', filename=file)
            msg.attach(msg_file)

    if not DEBUG:
        smtp.sendmail(addr, [addr], msg.as_string())

    smtp.quit()
